### ISSUE TITLE
CPT - Estimated Water Depth

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#17]
Another CPT related question - when transmitting CPT data, it would be useful to have the estimated water depth associated with the test in the DIGGS file.  Presumably this should go into the TestEvent.  However, in order to make that something that is useful and others would recognize we need standardized terminology for what the parameter is.  

In the Dictionary, we would need to add Estimated Water Depth as a property.  So this question is a cross between a question about schema and also the dictionary.

![cpt estimated water depth](https://user-images.githubusercontent.com/2412948/81968981-3bb82b00-95eb-11ea-9e4c-e076c526b2e5.PNG)

**Comment by dponti** [comment]
I see two options here:

1) If water depth may be estimated at different times while pushing the cone, then the water depth should be added to the event object - look at BoreholeEvent for an example. There is a specific SoundingEvent that probably should be used instead of InSituEvent, and we can add there.

If estimated water depth is something that would only be determined once for the sounding, then this isn't really an "event" - rather it's a property of the StaticConePenetrationTest, and we can simply add a waterDepth element to that object - see DrivenPenetrationTest for an example where we have a waterDepth property.

Please advise...

**Comment by dponti** [comment]
estimatedWaterDepth property added to StaticConePenetrationTest in 2.5.b branch. Water depths/elevations added to property class dictionary so thta calculated water depths from pore pressure dissipation tests can be reported there. PorePressureDissipationTest element also added to 2.5.b
