### ISSUE TITLE
SPT Test - Link to Sampling Activity

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/diggs-schema#30]
When you have a SPT test, how can it be related to a sampling activity? The Sampling Activity is where you have the Recovery Length as shown below, but the SPT blow counts are in the test object which doesn't seem to reference back to this activity.   

<samplingActivity>
				<SamplingActivity gml:id="SA_B-001-0-16_1">
					<gml:name>1</gml:name>
					<investigationTarget>Natural Ground</investigationTarget>
					<projectRef xlink:href="#OGE600304"/>
					<samplingFeatureRef xlink:href="#Borehole_B-001-0-16"/>
						<samplingLocation>
							<LinearExtent gml:id="DGSA77E-25C-1B4C-6FAA-1EFBA" srsDimension="1" srsName="#B-001-0-16-lsr">
								<gml:posList>1 2.5</gml:posList>
							</LinearExtent>
						</samplingLocation>
					<activityType>collect</activityType>
						<sampleProduced>
							<SampleProduced gml:id="SampleProduced_B-001-0-16_1_SS-1A">
								<location>
									<LinearExtent gml:id="DGS238C-51A-251E-ABB2-64A1D" srsDimension="1" srsName="#B-001-0-16_1_2.5-lsr">
										<gml:posList>1 2.5</gml:posList>
									</LinearExtent>
								</location>
							</SampleProduced>
						</sampleProduced>
						<samplingMethod>
							<Specification gml:id="DGS59F8-18A1-4845-5B3A-240A6">
								<gml:name codeSpace="ODOT_CS">SS</gml:name>
							</Specification>
						</samplingMethod>
						<totalSampleRecoveryLength uom="in">16</totalSampleRecoveryLength>
				</SamplingActivity>
			</samplingActivity>

An example of the XML would be helpful. Thanks in advance.

**Comment by dponti** [comment]
This is a good question with some important implications. There is currently no explicit referencing in DIGGS 2.5 (or presently in 2.6) between a sampling activity and a test, which is the feature under which one records results for an SPT as well as metadata for the test procedure (DrivenPenetrationTest object). This is because both tests and sampling activities cannot be targets of one another (eg. you can't test a sampling activity and conversely you can't sample a test). Logically, the blow counts and computed N value have nothing to do with the recovered length of the sample - the sample is an incidental result of the test procedure. The separate SamplingActivity feature therefore records the information relevant to obtaining the sample.

So at present, the only way to tie a particular sampling activity (and it's recovered sample) to the SPT test that incidentally recovered that sample via the DrivenPenetrationTest procedure object, is implicitly by location. Both the SamplingActivity that produced the sample and the Test reference the same borehole (sampleFeataureRef's are equivalent) and occur over the same depth range within the borehole (eg. the sampleLocation property of the samplingActivity feature and the location property of the Test). You can therefore associate the Test with the SamplingActivity programmatically in this way.

The actual association is between theDrivenPenetrationTest procedure object and the SamplingActivity. In fact, some of the properties (but not all) of the DrivenPenetrationTest procedure object is a specialization of a sampling activity and the fact that those properties are also conflated with properties pertinent to the test (eg. the specific blow count information) is admittedly problematic. Perhaps the structure of the DrivenPenetrationTest procedure object should be modified.

The simplest solution might be to add a samplingActivityRef property (optional so to not break existing instances) to the DrivenPenetrationTest procedure. This will tie the Test that the DrivenPenetrationTest object is contained within to the SamplingActivity and ultimately to the Sample that is collected. The reverse association which may be what is preferred (eg. sampling activity to test) is more problematic to do for reasons that we can discuss in another thread. So, I'm not sure that the simple solution is logically the best approach, although it's probably the least disruptive.

There's not really a logically simple solution to this that I can think of at the moment that doesn't alter the structure of existing schema objects. So my first question is - is it necessary for the two features (SamplingActivity and Test) to be explicitly linked through a referencing id, and if so what use cases require this and why? Assuming  the answer to the first question is yes, the what and why may help direct the best solution.

**Comment by dponti** [comment]
Thinking about this more, I believe the best logical association is from the SamplingActivity to the test procedure, since it's the SPT test procedure that was used to collect the sample. The SamplingActivity already has a samplingMethod property to define the method used to obtain the sample. That property currently can include or reference a Specification object. The Specification is essentially a generic procedure that has fields to refer to a specification or standard by name or where one can be defined.

We can develop an AbstractProcedure object from which both AbstractTestProcedure and Specification both inherit. This would allow the samplingMethod property to reference the DrivenPenetrationTest procedure of the Test (or any other procedure for that matter, including the Specification object). Since the test procedure is a component of the larger Test object one could traverse from the sample to the test result via the existing samplingMethod of the SamplingActivity object.

This will work without impacting existing xml instances. I'll implement in the test 2.6 schema and will let you know when it's uploaded.

**Comment by dponti** [comment]
The current commit of 2.6 (now 2.6-dev) will allow you to reference the gml:ID of the test procedure that is associated with the SamplingActivity (eg. DrivenPenetrationTest for SPT) within the overall Test object. You  do this by including the xlink:href attribute in the samplingMethod property of the SamplingActivity:
<SamplingActivity>
...
   <samplingMethod xlink:href="#spt-1"/>. 
...
</SamplingActivity>

**Comment by sdeaton75** [comment]
@dponti - Can you please provide an example of how this works in 2.6-dev? Thanks!

**Comment by dponti** [comment]
Using an example from the ODOT example file Example_2_20180702.xml, currently, the existing file's SamplingActivity objects that relate to the SPT tests include a Specification object within the samplingMethod property that identifies the samplingMethod to be SS - ODOT's code for Split-spoon sampling., eg:
	<samplingActivity>
		<SamplingActivity gml:id="SA_B-001-0-12_12"> 
...
		  <samplingMethod>
			<Specification gml:id="DGS5976-C1-3959-4FBE-66E48">
				<gml:name codeSpace="ODOT_CS">SS</gml:name>
			</Specification>
		  </samplingMethod>
                   <totalSampleRecoveryLength uom="in">14</totalSampleRecoveryLength> 
              </SamplingActivity>
	<samplingActivity>

The Test that holds the SPT blow count info obtained while collecting the sample, has a DrivenPenetrationTest test procedure object that both identifies the test, and contains the seating and interval blow counts (whereas the Test object itself reports the N values). Eg. 
	<Test gml:id="SPT_B-001-0-12_1.5">
...
          <outcome>
...
          </outcome>
          <procedure>
            <diggs_geo:DrivenPenetrationTest gml:id="DGS2746-119A-3DA6-204B-2D331">
              <diggs_geo:penetrationTestType>SPT</diggs_geo:penetrationTestType>
              <diggs_geo:totalPenetration uom="in">18</diggs_geo:totalPenetration>
 ...
            </diggs_geo:DrivenPenetrationTest>
          </procedure>
        </Test>

In 2.6, , to link the samplingActivity to the specific test performed that acquired the sample, you would simply reference the test procedure object in the SamplingActivity's samplingMethod property as follows, using the example above:

	<samplingActivity>
		<SamplingActivity gml:id="SA_B-001-0-12_12"> 
...
		  <samplingMethod xlink:href="#DGS2746-119A-3DA6-204B-2D331"/>
                   <totalSampleRecoveryLength uom="in">14</totalSampleRecoveryLength> 
                </SamplingActivity>
	<samplingActivity>

That's it. In 2.6, you can alternatively embed the entire <DrivenPenetrationTest> object within the <samplingMethod> property and reference that object in the <procedure> property of the test, if you wanted.

In fact, since the <samplingMethod> property in 2.5 allows reference to a Specification object (so you don't need to repeat the same object in different SamplingActivity instances), you can actually add the xlink:href reference to a test procedure object in 2.5 as above without causing a validation error. However, the inference in 2.5 is that the reference is to a Specification object only, and not to a Test procedure. That inference is removed in 2.6, and you can reference either a test procedure object or a Specification object as both not derive from the same abstract type.
